In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/ushape.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/ushape.csv'

In [3]:
df.head()

NameError: name 'df' is not defined

In [4]:
plt.scatter(df['X'],df['Y'],c=df['class'])

NameError: name 'df' is not defined

In [5]:
X = df.iloc[:,0:2].values
y = df.iloc[:,-1].values

NameError: name 'df' is not defined

In [6]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
model = Sequential()

model.add(Dense(10,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 41 (164.00 Byte)
Trainable params: 41 (164.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
# Set parameters to 0
model.get_weights()

[array([[-0.64482063, -0.4791397 , -0.61047786,  0.11291307,  0.664391  ,
          0.32683784, -0.48242226, -0.1972673 ,  0.42707008,  0.39587742],
        [-0.5777898 ,  0.53377026, -0.21648744, -0.6148766 ,  0.35704023,
          0.01934677, -0.58282214, -0.17362446,  0.3551064 ,  0.69663125]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.34248716],
        [-0.14484   ],
        [-0.0543229 ],
        [-0.5329908 ],
        [ 0.64134854],
        [ 0.5506955 ],
        [-0.12735099],
        [-0.6753299 ],
        [ 0.5170266 ],
        [ 0.6576176 ]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
initial_weights = model.get_weights()

In [10]:
initial_weights[0] = np.zeros(model.get_weights()[0].shape)
initial_weights[1] = np.zeros(model.get_weights()[1].shape)
initial_weights[2] = np.zeros(model.get_weights()[2].shape)
initial_weights[3] = np.zeros(model.get_weights()[3].shape)

In [11]:
model.set_weights(initial_weights)

In [12]:
model.get_weights()

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [14]:
history = model.fit(X,y,epochs=100,validation_split=0.2)

NameError: name 'X' is not defined

In [ ]:
model.get_weights()

In [ ]:
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X,y.astype('int'), clf=model, legend=2)